# Generated by Django 3.2.8 on 2021-10-16 11:08

from django.db import migrations
from django.db.migrations import migration


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO store_collection (title) VALUES ('collection1')""" , """DELETE FROM store_collection WHERE title = 'collection1'""")
    ]
